local watch_types = {
  "accumulator",
  "agricultural-tower",
  "assembling-machine",
  "asteroid-collector", -- no idea if there is network in space
  "beacon",
  "boiler",
  "burner-generator",
  "cargo-bay",
  "cargo-landing-pad",
  "container",
  "electric-turret",
  "furnace",
  "fusion-generator",
  "fusion-reactor",
  "generator",
  "inserter",
  "lab",
  "logistic-container",
  "mining-drill",
  "offshore-pump",
  "pump",
  "radar",
  "reactor",
  "roboport",
  "rocket-silo",
  "solar-panel",
  "storage-tank",
  "thruster", -- no idea if there is network in space
  "turret",
  "valve",
}

data:extend({
  {
    type = "string-setting",
    name = "aqu-watch-types",
    setting_type = "runtime-global",
    default_value = table.concat(watch_types, ", "),
    allow_blank = true,
  },
  {
    type = "string-setting",
    name = "aqu-tick-mode",
    setting_type = "runtime-global",
    allowed_values = {
      "cycle",
      "constant",
    },
    default_value = "cycle",
  },
  {
    type = "int-setting",
    name = "aqu-ticks-per-cycle",
    setting_type = "runtime-global",
    default_value = 600,
    minimum_value = 1,
  },
  {
    type = "int-setting",
    name = "aqu-on-nth-tick",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
  },
  {
    type = "int-setting",
    name = "aqu-entities-per-on-nth-tick",
    setting_type = "runtime-global",
    default_value = 42,
    minimum_value = 1,
  },
})
